version: '3.4'
services:
  server:
    container_name: ecommerce_server
    build:
      dockerfile: docker/Dockerfile
      context: .
    depends_on:
      - database
      - redis
    volumes:
      - ./:/app/server
      - /app/server/node_modules
    ports:
      - 5000:5000
    networks: 
      - backend
    
  database:
    image: mongo:4.4.2
    container_name: ecommerce_database
    depends_on:
      - redis
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    networks: 
      - backend

  redis:
    image: redis:6.0.9
    container_name: ecommerce_redis
    volumes:
      - redis-data:/data/redis
    ports:
      - 6379:6379
    networks:
      - backend
      
volumes:
  mongo-data:
  redis-data:

networks:
  backend: